# Generated by Django 5.2 on 2025-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateField()),
                ('charge_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('tag', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('charge_date',),
            },
        ),
    ]
