# Generated by Django 5.2 on 2025-04-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='charge_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='budget',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
