# Generated by Django 5.2 on 2025-04-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_budget_amount_alter_budget_charge_date_and_more'),
        ('users', '0002_userlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(blank=True, max_length=50, null=True)),
                ('common_matches1', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateField(null=True)),
                ('charge_name', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userlist', verbose_name='user')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.category', verbose_name='tag')),
            ],
            options={
                'ordering': ('charge_date',),
            },
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
